<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="5" failed="2" ignored="0" total="14" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="13184" started-at="2018-12-20T07:51:52Z" finished-at="2018-12-20T07:52:06Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="13184" started-at="2018-12-20T07:51:52Z" finished-at="2018-12-20T07:52:06Z">
      <class name="seleniumdemo.BatchFileOne$SkipTestCase">
        <test-method status="PASS" signature="testone()[pri:0, instance:seleniumdemo.BatchFileOne$SkipTestCase@8bd1b6a]" name="testone" duration-ms="1" started-at="2018-12-20T07:52:03Z" finished-at="2018-12-20T07:52:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testone -->
        <test-method status="SKIP" signature="testtwo()[pri:0, instance:seleniumdemo.BatchFileOne$SkipTestCase@8bd1b6a]" name="testtwo" duration-ms="5" started-at="2018-12-20T07:52:03Z" finished-at="2018-12-20T07:52:03Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[message]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: message
at seleniumdemo.BatchFileOne$SkipTestCase.testtwo(BatchFileOne.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testtwo -->
        <test-method status="SKIP" signature="testthree()[pri:0, instance:seleniumdemo.BatchFileOne$SkipTestCase@8bd1b6a]" name="testthree" duration-ms="0" started-at="2018-12-20T07:52:03Z" depends-on-methods="seleniumdemo.BatchFileOne$SkipTestCase.testtwo" finished-at="2018-12-20T07:52:03Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BatchFileOne$SkipTestCase.testthree()[pri:0, instance:seleniumdemo.BatchFileOne$SkipTestCase@8bd1b6a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BatchFileOne$SkipTestCase.testthree()[pri:0, instance:seleniumdemo.BatchFileOne$SkipTestCase@8bd1b6a] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testthree -->
      </class> <!-- seleniumdemo.BatchFileOne$SkipTestCase -->
      <class name="seleniumdemo.AnnotationFacebook">
        <test-method status="PASS" signature="launchbrauser()[pri:0, instance:seleniumdemo.AnnotationFacebook@4678c730]" name="launchbrauser" is-config="true" duration-ms="10386" started-at="2018-12-20T07:51:52Z" finished-at="2018-12-20T07:52:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchbrauser -->
        <test-method status="PASS" signature="beforetest()[pri:0, instance:seleniumdemo.TestNgTesting@724af044]" name="beforetest" is-config="true" duration-ms="0" started-at="2018-12-20T07:52:03Z" finished-at="2018-12-20T07:52:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetest -->
        <test-method status="PASS" signature="logincheck()[pri:0, instance:seleniumdemo.AnnotationFacebook@4678c730]" name="logincheck" duration-ms="476" started-at="2018-12-20T07:52:03Z" finished-at="2018-12-20T07:52:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logincheck -->
        <test-method status="PASS" signature="closebrowser()[pri:0, instance:seleniumdemo.AnnotationFacebook@4678c730]" name="closebrowser" is-config="true" duration-ms="2174" started-at="2018-12-20T07:52:03Z" finished-at="2018-12-20T07:52:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closebrowser -->
        <test-method status="PASS" signature="aftertest()[pri:0, instance:seleniumdemo.TestNgTesting@724af044]" name="aftertest" is-config="true" duration-ms="1" started-at="2018-12-20T07:52:06Z" finished-at="2018-12-20T07:52:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftertest -->
      </class> <!-- seleniumdemo.AnnotationFacebook -->
      <class name="seleniumdemo.BatchFileThree$SkipTestCase">
        <test-method status="PASS" signature="testfour()[pri:0, instance:seleniumdemo.BatchFileThree$SkipTestCase@6767c1fc]" name="testfour" duration-ms="8" started-at="2018-12-20T07:52:03Z" finished-at="2018-12-20T07:52:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testfour -->
        <test-method status="PASS" signature="testone()[pri:0, instance:seleniumdemo.BatchFileThree$SkipTestCase@6767c1fc]" name="testone" duration-ms="1" started-at="2018-12-20T07:52:03Z" finished-at="2018-12-20T07:52:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testone -->
        <test-method status="SKIP" signature="testtwo()[pri:0, instance:seleniumdemo.BatchFileThree$SkipTestCase@6767c1fc]" name="testtwo" duration-ms="4" started-at="2018-12-20T07:52:03Z" finished-at="2018-12-20T07:52:03Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[message]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: message
at seleniumdemo.BatchFileThree$SkipTestCase.testtwo(BatchFileThree.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testtwo -->
      </class> <!-- seleniumdemo.BatchFileThree$SkipTestCase -->
      <class name="seleniumdemo.SkipTestCase">
        <test-method status="SKIP" signature="testtwo()[pri:0, instance:seleniumdemo.SkipTestCase@c038203]" name="testtwo" duration-ms="2" started-at="2018-12-20T07:52:03Z" finished-at="2018-12-20T07:52:03Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[message]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: message
at seleniumdemo.SkipTestCase.testtwo(SkipTestCase.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testtwo -->
        <test-method status="PASS" signature="testfour()[pri:0, instance:seleniumdemo.SkipTestCase@c038203]" name="testfour" duration-ms="0" started-at="2018-12-20T07:52:03Z" finished-at="2018-12-20T07:52:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testfour -->
        <test-method status="PASS" signature="testone()[pri:0, instance:seleniumdemo.SkipTestCase@c038203]" name="testone" duration-ms="1" started-at="2018-12-20T07:52:03Z" finished-at="2018-12-20T07:52:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testone -->
        <test-method status="SKIP" signature="testthree()[pri:0, instance:seleniumdemo.SkipTestCase@c038203]" name="testthree" duration-ms="0" started-at="2018-12-20T07:52:03Z" depends-on-methods="seleniumdemo.SkipTestCase.testtwo" finished-at="2018-12-20T07:52:03Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SkipTestCase.testthree()[pri:0, instance:seleniumdemo.SkipTestCase@c038203] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SkipTestCase.testthree()[pri:0, instance:seleniumdemo.SkipTestCase@c038203] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testthree -->
      </class> <!-- seleniumdemo.SkipTestCase -->
      <class name="seleniumdemo.BatchFileTwo">
        <test-method status="FAIL" signature="method1()[pri:0, instance:seleniumdemo.BatchFileTwo@29ee9faa]" name="method1" duration-ms="11" started-at="2018-12-20T07:52:03Z" finished-at="2018-12-20T07:52:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Abhay] but found [veena]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Abhay] but found [veena]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at seleniumdemo.BatchFileTwo.method1(BatchFileTwo.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method1 -->
        <test-method status="FAIL" signature="method2()[pri:0, instance:seleniumdemo.BatchFileTwo@29ee9faa]" name="method2" duration-ms="5" started-at="2018-12-20T07:52:03Z" finished-at="2018-12-20T07:52:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Abhay] but found [veena]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Abhay] but found [veena]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at seleniumdemo.BatchFileTwo.method2(BatchFileTwo.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method2 -->
        <test-method status="PASS" signature="method3()[pri:0, instance:seleniumdemo.BatchFileTwo@29ee9faa]" name="method3" duration-ms="5" started-at="2018-12-20T07:52:03Z" finished-at="2018-12-20T07:52:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method3 -->
      </class> <!-- seleniumdemo.BatchFileTwo -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
